database_url = URI::Generic.build(
  scheme: "postgres",
  userinfo: "#{ENV['DB_USER']}:#{ENV['DB_PASSWORD']}",
  host: ENV["DB_HOST"],
  port: 5432,
  path: "/#{ENV['DB_NAME']}"
).to_s


namespace :db do
  desc "Run migrations"
  task :migrate, [:version] do |t, args|
    require "sequel/core"
    Sequel.extension :migration
    version = args[:version].to_i if args[:version]
    Sequel.connect(database_url) do |db|
      Sequel::Migrator.run(db, "db/migrations", target: version)
    end
  end
end

task :environment do
  require_relative "./config/initializers/base.rb"
end

task :console => [:environment] do
  require 'irb'
  binding.irb
end
